### PR TITLE
Write steps in correct order, add titles. Fix StepicOrg/Stepik-API/is…

### PR DESCRIPTION
**Pull request by nkgsv**
Write course steps in correct order. This fixes issue #49

### CODE REVIEW

**Comment by mehanig** [comment]
So, the problem occur because there is no guarantee of order when using https://github.com/nkgsv/Stepik-API/blob/93fc7afa2c4259d2fb1f9854a77229f80a2be255/examples/save_course_steps.py#L32 fetch_objects function. If you ask for objects with order `ids[]=1&ids[]=2`, response will be same as for asking `ids[]=2&ids[]=1`

Correct way to fix this problem is to reorder objects after response and return list with preserved ids order.

If you want to fix this bug, you should fix `fetch_objects` function, other code is not related to that problem.

**Comment by nkgsv** [comment]
Exactly, this is the source of the problem.

Originally I wanted to reorder the objects in `fetch_objects` as you proposed. But then I thought that this might be not the best solution. For instance, if we want to include the titles of the modules and lessons in the resulting HTML, then it is not sufficient to order the steps in the correct way: the steps do not contain information about lessons and modules. So, anyway we have to iterate modules and lessons, and I've modified the file output code accordingly. But if you prefer, then of course we can just fix `fetch_objects`, at least for this issue. What do you think?

**Comment by mehanig** [comment]
It's better to change it in one place
I'm thinking about to change signature of  fetch_objects from `def fetch_objects(obj_class, obj_ids):` to `def fetch_objects(obj_class, obj_ids, keep_order=False):` and reorder if needed

**Comment by nkgsv** [comment]
Moved to #53

**Pull request closed without merging**
